name: CI

on: [push, pull_request]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2
      - name: set up conda
      - run : |
	  if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
	      wget https://repo.continuum.io/miniconda/Miniconda2latest-Linux-x86_64.sh -O miniconda.sh;
	    else
	      wget https://repo.continuum.io/miniconda/Miniconda3latest-Linux-x86_64.sh -O miniconda.sh;
	    fi
	  bash miniconda.sh -b -p $HOME/miniconda
	  source "$HOME/miniconda/etc/profile.d/conda.sh"
	  hash -r
	  conda config --set always_yes yes --set changeps1 no
	  conda update -q conda
	  # Useful for debugging any issues with conda
	  conda info -a
	
	  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION rdflib requests parameterized jupyter nose2 -c conda-forge
	  conda activate test-environment
	
      - name: Set up 
        run: |
          git clone https://github.com/edamontology/edamverify.git
          cd edamverify
          echo "nose2" >>  ci_test/requirements.txt
          pip install -r ci_test/requirements.txt
          wget http://www.hermit-reasoner.com/download/current/HermiT.zip && unzip -o -d . HermiT.zip HermiT.jar
 
      - name: Run scripts  
        run: |
          export EDAM_PATH=../edamontology/EDAM_dev.owl 
          nose2 --with-coverage --verbose ci_test.test_edamxpathvalidator
          nose2 --with-coverage --verbose ci_test.test_hermit
