name: Hermit test 

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2
      - name: install hermit  
        run: wget http://www.hermit-reasoner.com/download/current/HermiT.zip && unzip -o -d . HermiT.zip HermiT.jar

      - name: Run hermit  
        run: java -jar HermiT.jar ../edamontology/EDAM_dev.owl --verbose 
