name: JSON GENERATION

on:
  pull_request_target:
    types:
      - closed
    paths:
      - 'EDAM_dev.owl'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
      - run: |
          echo The PR was merged
