name: ROBOT

on:
  push:
    branches: [ validation ]
  pull_request:
    branches: [ validation ]
jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up 
      run: |
        git clone https://github.com/edamontology/edamverify.git

    - name: run reason
      run: |
        export PATH=/home/runner/work/edamontology/edamontology/edamverify/robot:$PATH
        robot reason --reasoner ELK   --input EDAM_dev.owl -v 

    - name: run report 
      run: |
        cd edamverify/robot/
        export PATH=:/home/runner/work/edamontology/edamontology/edamverify/robot:$PATH
        robot report --input ../../EDAM_dev.owl --output report_profile.tsv --profile edamverify/robot/report_queries.txt
