name: sandbox tests

on: 
  workflow_dispatch:

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: run bash
      if: always()
      run: |
        cd .github/workflows
        ./sandbox.sh bad_uri

